import type { Vehicle, Salesperson } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const mockSalespeople: Salesperson[] = [
    {
        id: 'sp-1',
        name: 'Admin',
        email: 'admin@alziatrading.com',
    },
    {
        id: 'sp-2',
        name: 'Jane Doe',
        email: 'jane.doe@alziatrading.com',
    }
];


export const mockVehicles: Vehicle[] = [
  {
    id: 'vehicle-1',
    make: 'Toyota',
    model: 'Mark X',
    year: 2022,
    referenceNumber: 'AT-83628',
    chassisNumber: 'GRX130-12345',
    drivetrain: 'RWD',
    transmission: 'Automatic',
    color: 'Pearl White',
    fuel: 'Petrol',
    vehicleType: 'Sedan',
    mileage: 15000,
    condition: 'Used',
    price: 25000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-1-1', url: getImage('car-1-1')?.imageUrl || '', isFeature: true },
      { id: 'img-1-2', url: getImage('car-1-2')?.imageUrl || '', isFeature: false },
    ],
  },
  {
    id: 'vehicle-2',
    make: 'Nissan',
    model: 'GT-R Nismo',
    year: 2023,
    referenceNumber: 'AT-91734',
    chassisNumber: 'R35-67890',
    drivetrain: 'AWD',
    transmission: 'Automatic',
    color: 'Stealth Gray',
    fuel: 'Petrol',
    vehicleType: 'Coupe',
    mileage: 5000,
    condition: 'Used',
    price: 150000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-2-1', url: getImage('hero-nissan')?.imageUrl || '', isFeature: true },
      { id: 'img-2-2', url: getImage('car-2-2')?.imageUrl || '', isFeature: false },
    ],
  },
  {
    id: 'vehicle-3',
    make: 'Honda',
    model: 'Fit',
    year: 2021,
    referenceNumber: 'AT-10293',
    chassisNumber: 'GK3-12312',
    drivetrain: 'FWD',
    transmission: 'Automatic',
    color: 'Electric Blue',
    fuel: 'Hybrid',
    vehicleType: 'Hatchback',
    mileage: 25000,
    condition: 'Used',
    price: 18000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-3-1', url: getImage('car-3-1')?.imageUrl || '', isFeature: true },
      { id: 'img-3-2', url: getImage('car-3-2')?.imageUrl || '', isFeature: false },
    ],
  },
  {
    id: 'vehicle-4',
    make: 'Subaru',
    model: 'WRX STI',
    year: 2020,
    referenceNumber: 'AT-48392',
    chassisNumber: 'VAB-45678',
    drivetrain: 'AWD',
    transmission: 'Manual',
    color: 'WR Blue Pearl',
    fuel: 'Petrol',
    vehicleType: 'Sedan',
    mileage: 35000,
    condition: 'Used',
    price: 42000,
    currency: 'USD',
    status: 'Incoming',
    inspectionStatus: 'Pending',
    images: [
        { id: 'img-4-1', url: getImage('hero-subaru')?.imageUrl || '', isFeature: true },
    ],
  },
  {
    id: 'vehicle-5',
    make: 'Lexus',
    model: 'RX 450h',
    year: 2022,
    referenceNumber: 'AT-51515',
    chassisNumber: 'GYL25-98765',
    drivetrain: 'AWD',
    transmission: 'Automatic',
    color: 'Black',
    fuel: 'Hybrid',
    vehicleType: 'SUV',
    mileage: 22000,
    condition: 'Used',
    price: 55000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
        { id: 'img-5-1', url: getImage('car-5-1')?.imageUrl || '', isFeature: true },
    ],
  },
   {
    id: 'vehicle-6',
    make: 'Volkswagen',
    model: 'Golf R',
    year: 2021,
    referenceNumber: 'AT-72635',
    chassisNumber: 'VW-GOLF-R21',
    drivetrain: 'AWD',
    transmission: 'Automatic',
    color: 'Lapiz Blue',
    fuel: 'Petrol',
    vehicleType: 'Hatchback',
    mileage: 18000,
    condition: 'Used',
    price: 45000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-6-1', url: 'https://images.unsplash.com/photo-1629587239634-2a626c7a61f2?q=80&w=2070&auto=format&fit=crop', isFeature: true },
    ]
  },
  {
    id: 'vehicle-7',
    make: 'Toyota',
    model: 'Supra',
    year: 2023,
    referenceNumber: 'AT-44821',
    chassisNumber: 'A90-SUPRA-23',
    drivetrain: 'RWD',
    transmission: 'Automatic',
    color: 'Renaissance Red',
    fuel: 'Petrol',
    vehicleType: 'Coupe',
    mileage: 3000,
    condition: 'New',
    price: 68000,
    currency: 'USD',
    status: 'Sold',
    inspectionStatus: 'Passed',
    saleDate: '2024-05-15',
    buyerDetails: 'John Smith',
    finalPrice: 67500,
    images: [
      { id: 'img-7-1', url: getImage('hero-toyota')?.imageUrl || '', isFeature: true },
    ],
  },
  {
    id: 'vehicle-8',
    make: 'Mazda',
    model: 'CX-5',
    year: 2022,
    referenceNumber: 'AT-33910',
    chassisNumber: 'KF-CX5-5555',
    drivetrain: 'AWD',
    transmission: 'Automatic',
    color: 'Soul Red Crystal',
    fuel: 'Diesel',
    vehicleType: 'SUV',
    mileage: 31000,
    condition: 'Used',
    price: 29000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-8-1', url: 'https://images.unsplash.com/photo-1617469767053-13b318a8f7e2?q=80&w=2070&auto=format&fit=crop', isFeature: true },
    ]
  },
  {
    id: 'vehicle-9',
    make: 'Suzuki',
    model: 'Jimny',
    year: 2023,
    referenceNumber: 'AT-66789',
    chassisNumber: 'JB74-12345',
    drivetrain: '4x4',
    transmission: 'Manual',
    color: 'Kinetic Yellow',
    fuel: 'Petrol',
    vehicleType: 'SUV',
    mileage: 8000,
    condition: 'Used',
    price: 24000,
    currency: 'USD',
    status: 'Incoming',
    inspectionStatus: 'Pending',
    images: [
      { id: 'img-9-1', url: getImage('car-6-1')?.imageUrl || '', isFeature: true },
    ]
  },
  {
    id: 'vehicle-10',
    make: 'Mitsubishi',
    model: 'Pajero',
    year: 2019,
    referenceNumber: 'AT-11234',
    chassisNumber: 'V97W-PAJERO',
    drivetrain: '4x4',
    transmission: 'Automatic',
    color: 'Silver',
    fuel: 'Diesel',
    vehicleType: 'SUV',
    mileage: 75000,
    condition: 'Used',
    price: 32000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-10-1', url: 'https://images.unsplash.com/photo-1603584848380-5ac937d324c4?q=80&w=2070&auto=format&fit=crop', isFeature: true },
    ]
  },
  {
    id: 'vehicle-11',
    make: 'Isuzu',
    model: 'D-Max',
    year: 2021,
    referenceNumber: 'AT-22456',
    chassisNumber: 'RG01-ISUZU',
    drivetrain: '4x4',
    transmission: 'Automatic',
    color: 'Obsidian Gray',
    fuel: 'Diesel',
    vehicleType: 'Pickup',
    mileage: 45000,
    condition: 'Used',
    price: 38000,
    currency: 'USD',
    status: 'Available',
    inspectionStatus: 'Passed',
    images: [
      { id: 'img-11-1', url: 'https://images.unsplash.com/photo-1631728362630-363e1a81d638?q=80&w=1974&auto=format&fit=crop', isFeature: true },
    ]
  },
  {
    id: 'vehicle-12',
    make: 'Land Rover',
    model: 'Defender 110',
    year: 2022,
    referenceNumber: 'AT-99876',
    chassisNumber: 'L663-DEFENDER',
    drivetrain: '4x4',
    transmission: 'Automatic',
    color: 'Pangea Green',
    fuel: 'Petrol',
    vehicleType: 'SUV',
    mileage: 12000,
    condition: 'Used',
    price: 85000,
    currency: 'USD',
    status: 'Sold',
    inspectionStatus: 'Passed',
    saleDate: '2024-06-01',
    buyerDetails: 'Alice Wonderland',
    finalPrice: 84000,
    images: [
      { id: 'img-12-1', url: 'https://images.unsplash.com/photo-1677643323343-539c4d92d194?q=80&w=2070&auto=format&fit=crop', isFeature: true },
    ]
  }
];
